#ifndef  __CONFIG_H__
#define  __CONFIG_H__

#define CONFIG_SGL_PANEL_PIXEL_DEPTH 16
#define CONFIG_SGL_COLOR16_SWAP 1
#define CONFIG_SGL_EVENT_QUEUE_SIZE 16
#define CONFIG_SGL_OBJ_SLOT_DYNAMIC 1
#define CONFIG_SGL_ANIMATION 1
#define CONFIG_SGL_ANIMATION_TICK_MS 10
#define CONFIG_SGL_DEBUG 0
#define CONFIG_SGL_LOG_COLOR 1
#define CONFIG_SGL_LOG_LEVEL 0
#define CONFIG_SGL_USE_OBJ_ID 1
#define CONFIG_SGL_USE_STYLE_UNIFIED_API 1
#define CONFIG_SGL_THEME_DEFAULT 1
#define CONFIG_SGL_HEAP_ALGO other
#define CONFIG_SGL_FL_INDEX_MAX 20
#define CONFIG_SGL_HEAP_MEMORY_SIZE 0
#define CONFIG_SGL_FONT_SONG23 1
#define CONFIG_SGL_FONT_CONSOLAS23 0
#define CONFIG_SGL_FONT_KAI33 0
#define CONFIG_SGL_DRAW_USE_DMA 0

#endif
